### ISSUE TITLE
Update Line Duplication Productivity extension to VS 2022

### ISSUE THREAD

**Issue by arthursoprana** [neptuo/Productivity#81]
Hi,

Since VS 2022 Preview is already [available](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-1-now-available/). Do you have any plans to update this extension to VS 2022?

It seems that [there is already a guide for updating the extensions](https://aka.ms/vssdk/2022/updateguide).

Thanks in advance 😃

**Comment by maraf** [comment]
Hello,

I will definitely update it, but I haven't entered the VS 2022 train yet, so no date or anything yet.
